apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{"pv.kubernetes.io/bind-completed":"yes","pv.kubernetes.io/bound-by-controller":"yes","volume.beta.kubernetes.io/storage-provisioner":"cephfs.csi.ceph.com","volume.kubernetes.io/storage-provisioner":"cephfs.csi.ceph.com"},"creationTimestamp":"2025-07-14T07:45:54Z","finalizers":["kubernetes.io/pvc-protection"],"name":"satis-output-pvc","namespace":"satis","resourceVersion":"1800474","uid":"a2bc023d-0050-4017-971e-caff856fa958"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"25Gi"}},"storageClassName":"cephfs-sc","volumeMode":"Filesystem","volumeName":"pvc-a2bc023d-0050-4017-971e-caff856fa958"},"status":{"accessModes":["ReadWriteOnce"],"capacity":{"storage":"25Gi"},"conditions":[{"lastProbeTime":null,"lastTransitionTime":"2025-07-14T13:11:47Z","status":"True","type":"Resizing"},{"lastProbeTime":null,"lastTransitionTime":"2025-07-14T13:11:47Z","message":"failed to expand pvc with rpc error: code = InvalidArgument desc = provided secret is empty","status":"True","type":"ControllerResizeError"}],"phase":"Bound"}}
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: cephfs.csi.ceph.com
    volume.kubernetes.io/storage-provisioner: cephfs.csi.ceph.com
  creationTimestamp: "2025-07-14T07:45:54Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: satis-output-pvc
  namespace: satis
  resourceVersion: "1800774"
  uid: a2bc023d-0050-4017-971e-caff856fa958
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  storageClassName: cephfs-sc
  volumeMode: Filesystem
  volumeName: pvc-a2bc023d-0050-4017-971e-caff856fa958
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-07-14T13:13:44Z"
    status: "True"
    type: Resizing
  - lastProbeTime: null
    lastTransitionTime: "2025-07-14T13:13:44Z"
    message: 'failed to expand pvc with rpc error: code = InvalidArgument desc = provided
      secret is empty'
    status: "True"
    type: ControllerResizeError
  phase: Bound
